name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: shaikayan13
          outputs: |
            dist/github-snake.svg?color_snake=purple&color_dots=#2e1065,#4c1d95,#6d28d9,#7c3aed,#a78bfa
            dist/github-snake-dark.svg?color_snake=purple&color_dots=#2e1065,#4c1d95,#6d28d9,#7c3aed,#a78bfa

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
